name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Run Linter
      run: php -l api.php

    - name: Run tests (if you have tests)
      run: |
        echo "No tests yet, just placeholder step"